version: '3.8'

services:
  api-dotnet:
    build:
      context: ./Test_Reminder_Flow_Monolegal_Backend_New
      dockerfile: Dockerfile
    container_name: reminder_flow_api_dotnet
    ports:
      - "8002:8000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDb__ConnectionString=mongodb://mongodb:27017
      - MongoDb__DatabaseName=reminder_flow_db
      - Redis__ConnectionString=redis:6379
      - Email__SmtpHost=smtp.gmail.com
      - Email__SmtpPort=587
      - Email__SmtpUser=juanjosefigueroahurtatis@gmail.com
      - Email__SmtpPassword=fnbr neqk xuhk qquo
      - Email__FromEmail=juanjosefigueroahurtatis@gmail.com
      - Email__FromName=Reminder Flow System
    depends_on:
      - mongodb
      - redis
    networks:
      - reminder_network

  frontend:
    build:
      context: ./Test_Reminder_Flow_Monolegal_Frontend
      dockerfile: Dockerfile
    container_name: reminder_flow_frontend
    ports:
      - "4200:80"
    depends_on:
      - api-dotnet
    networks:
      - reminder_network

  mongodb:
    image: mongo:7.0
    container_name: reminder_flow_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - reminder_network

  redis:
    image: redis:7-alpine
    container_name: reminder_flow_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - reminder_network

volumes:
  mongodb_data:
  redis_data:

networks:
  reminder_network:
    driver: bridge
